### ISSUE TITLE
Ability to use external g2c

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-MDL/grib2io#28]
What would it take to use an external g2c instead of building it internally? Is there some feature missing from the main repo? Building with Spack it would be ideal to use an external g2c so that there's no possibility of duplicate versions.

**Comment by eengl** [comment]
I think all that is needed is the ability to build g2c as a shared object library alongside the static lib.  A few weeks ago, I tried to play around with the g2c Cmake config, to see if I could get it make a shared object and static libs and got nowhere.

**Comment by kgerheiser** [comment]
Added that option here: https://github.com/NOAA-EMC/NCEPLIBS-g2c/pull/254

Can I set some variables for `setup.py` for the location of these libraries?

**Comment by eengl** [comment]
Sure!  Feel free to contribute as needed.

**Comment by kgerheiser** [comment]
Sorry, I meant that as a question. Now that I have an external shared library, how do I tell `setup.py` to use it? Or does that feature have to be added?

**Comment by eengl** [comment]
In setup.py, you can use one of the optional image compression library configurations for configuring g2c.  But as I give it more thought, the setup.py, I think, would need significant modifications.  The reason is since we now linking to an external g2c, the image compression libraries are no longer needed inside grib2io's setup.py since they should be accounted for in g2c's build.

I can take a shot modifying setup.py if you want.
